version: "3"

services:

    redis:
        image: redis:latest
        container_name: chat-demo.redis
        environment:
          - REDIS_REPLICATION_MODE=master
        ports:
          - "16379:6379"
        #volumes:
        #  - ./data/redis_db/data:/var/lib/redis
        #  - ./data/redis_db/conf:/usr/local/etc/redis/redis.conf
        command: redis-server --requirepass redis123

