version: "3"

services:

    redis:
        image: redis:latest
        container_name: chat-demo.redis
        environment:
          - REDIS_REPLICATION_MODE=master
        ports:
          - "16379:6379"
        command: redis-server --requirepass redis123

